default_language_version:
  python: python3.8
default_stages: [commit, push]
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black python formatting
        types_or: [python, pyi]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Flake8 python linter
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
